# Dockerfile.nginx
FROM nginx:1.25-alpine

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./nginx/proxy_params_common /etc/nginx/proxy_params_common

COPY ./adminapp/frontend/dist /usr/share/nginx/html


