# version: "3.9"

services:
  login-app:
    build:
      context: ./loginapp
    container_name: fake-login-login-app
    ports:
      - "${LOGIN_PORT}:8080"
    environment:
      - LOG_FILE=${LOG_PATH}
    volumes:
      - ./data:/data

  admin-app:
    build:
      context: ./adminapp
    container_name: fake-login-admin-app
    ports:
      - "${ADMIN_PORT}:8080"
    environment:
      - LOG_FILE=${LOG_PATH}
    volumes:
      - ./data:/data
