# version: "3.9"

services:
  postgres-db:
    image: postgres:16
    container_name: fake-login-postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "15432:5432"
    volumes:
      # - ./data/db:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data
      - ./pg_backup:/backup
    # 監控DB是否建好
    healthcheck:   
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  # login-app:
  #   build:
  #     context: ./loginapp
  #   container_name: fake-login-login-app
  #   ports:
  #     - "${LOGIN_PORT}:8080"
  #   environment:
  #     - LOG_FILE=${LOG_PATH}
  #   volumes:
  #     - ./loginapp/Logger:/app/Logger
  #   # 監控DB是否建好，建好再連線
  #   depends_on:
  #     postgres-db:
  #       condition: service_healthy


  admin-app:
    build:
      context: ./adminapp
    container_name: fake-login-admin-app
    ports:
      - "${ADMIN_PORT}:8080"
    volumes:
      - ./adminapp/Logger:/app/Logger
      - ./adminapp/app/certs:/app/app/certs
    # 監控DB是否建好，建好再連線
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  pgdata: